version: '3.9'

networks:
  app-network:


services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: '9Jc9]lA0s'
      POSTGRES_DB: horse
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    env_file: .env.prod
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: >
      sh -c "npx prisma migrate deploy &&
             pnpm run start:prod"
    networks:
      - app-network

volumes:
  pgdata:
